src/objects/ExchangeRate__c.object
<CustomObject>
    <fields>
        <fullName>BaseCurrency__c</fullName>
        <label>Base Currency</label>
        <length>3</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Rate__c</fullName>
        <label>Rate</label>
        <precision>18</precision>
        <required>true</required>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ToCurrency__c</fullName>
        <label>To Currency</label>
        <length>3</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>forList__c</fullName>
        <defaultValue>false</defaultValue>
        <label>For List</label>
        <type>Checkbox</type>
    </fields>
    <label>Exchange Rate</label>
    <nameField>
        <label>Currency Rates Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exchange Rates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TH_ExchangeRateDao.cls
public class TH_ExchangeRateDao {
	public void doInsert(List<ExchangeRate__c> exchangeRateList) {
		insert exchangeRateList;
	}
	
	public List<ExchangeRate__c> getRates() {
		return [ 
			SELECT createdDate
			FROM ExchangeRate__c
			WHERE baseCurrency__c IN :TH_ExchangeRateWebServiceWrapper.baseCurrencyList   
				AND forList__c = true  
			ORDER BY createdDate DESC
			LIMIT 1
		];
	}
	
	public List<ExchangeRate__c>  getTodaysRates() {
		return [ 
			SELECT id, baseCurrency__c, toCurrency__c, rate__c
			FROM ExchangeRate__c
			WHERE baseCurrency__c IN :TH_ExchangeRateWebServiceWrapper.baseCurrencyList   
				AND forList__c = true
				AND createdDate = TODAY  
		];
	}
}