src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Discount_Type__c</fullName>
        <label>Discount Type</label>
        <picklist>
            <picklistValues>
                <fullName>Brokerage allowance</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Bulk</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Card</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cash</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Coupons</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cumulative quantity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Disability</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dollar Value</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Educational or student</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Employee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Forward dating</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Military</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-cumulative quantity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partial payment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Percentage Based</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Preferred payment method</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Promotional allowances</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prompt payment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quantity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rebates</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Seasonal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Senior</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Settlement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sliding scale</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Special prices offered to friends of the seller</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Special prices offered to local residents</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Toddler / child / kid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trade</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trade-in credit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trade rate</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Discount_Type__c</fullName>
        <label>Discount Type</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Opportunity Settings</label>
</CustomObject>

src/classes/TH_Opportunities.cls
public class TH_Opportunities {
	DAO_UnitOfWork unitOfWork;
	List<Opportunity> opportunityList; 
	Map<Id, Decimal> discountPercentageByOpportunityId;
	DAO_AccountDao accountDao;
	
	public TH_Opportunities(
			List<Opportunity> opportunityList, 
			fflib_SObjectUnitOfWork unitOfWork, 
			Map<Id, Decimal> discountPercentageByOpportunityId, 
			DAO_AccountDao accountDao
		){
		this.opportunityList = opportunityList; 
		this.discountPercentageByOpportunityId = discountPercentageByOpportunityId;
		this.accountDao = accountDao;
		this.unitOfWork = new DAO_UnitOfWork(unitOfWork);
	}

	public TH_Opportunities(List<Opportunity> opportunityList, fflib_SObjectUnitOfWork unitOfWork) {
		this(
			opportunityList, 
			unitOfWork, 
			TH_OpportunitiesDefaultDiscounter.getDefaultDiscountMap(opportunityList), 
			new DAO_AccountDao()
		);
	}
	
	// ---------------------------------------------------------------------------------------

	public TH_Opportunities setDefaultDiscountTypes(){
		for (Opportunity opportunity : this.opportunityList) {
			if (opportunity.discountType__c == null) {
				opportunity.discountType__c = Opportunity_Settings__c.getInstance().discount_type__c;
				if (opportunity.id != null){
					unitOfWork.register(opportunity);
				} else {
					unitOfWork.register(opportunity);
				}
			}
		}
		return this;
	}

	public TH_Opportunities applyDiscounts(List<Decimal> discountList){
		for(Opportunity opportunity: opportunityList) {
			Decimal discountPercentage = this.discountPercentageByOpportunityId.get(opportunity.id);
			Decimal factor = 1 - (discountPercentage == null ? 0 : discountPercentage / 100);
			
			TH_OpportunitiesLineItemDiscountStrategy discountStrategy = 
				new TH_OpportunitiesLineItemDiscountStrategy(this.unitOfWork, opportunity, factor, discountList);
					 
			discountStrategy.execute(opportunity.opportunityLineItems); 
		} 
		return this;  
	}

	public TH_Opportunities updateOpportunityActivity(){ 
		List<Id> accountIdList = new List<Id>();
		for (Opportunity opportunity : this.opportunityList) {
			if (opportunity.accountId != null) {
				accountIdList.add(opportunity.accountId);
			}
		}
		
		TH_Accounts accounts = new TH_Accounts(accountDao.getByIds(accountIdList), unitOfWork);  
		accounts.updateOpportunityActivity();
		return this;
	}
	
	// ------------------------------------------------------------------------------
	
	public TH_Opportunities createWonFollowUpTask(){
		List <Task> newTaskList = new List<Task>();
		for(Opportunity opportunity : this.opportunityList) {
			if (opportunity.stageName == 'Closed Won') {
				Task task = new Task (
					subject = 'Follow Up Test Task',
					whatId = opportunity.id
				);
				newTaskList.add(task);
			}
		}
		insert newTaskList;
		return this;		
	}
}