src/objects/SmsLog__c.object
<CustomObject>
    <fields>
        <fullName>MessageResult__c</fullName>
        <label>Message Result</label>
        <length>160</length>
        <type>Text</type>
    </fields>
    <label>SMS Log</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{0000}</displayFormat>
        <label>SMS Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SMS Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TH_SmsWebServiceCalloutUtilTest.cls
@isTest
private class TH_SmsWebServiceCalloutUtilTest {
	private static final User TestRunner = TEST_RunAsUserFactory.create(); 
	
	@isTest static void testSendSms(){
		// Arrange
		Test.setMock(HttpCalloutMock.class, new TH_SmsWebServiceCalloutMock());

		String testFrom = '111';
		String testTo = '222';
		String testMessage = 'Greetings!';

		// Act
        System.runAs(TestRunner){
            Test.startTest();
            {
                TH_SmsWebServiceCalloutUtil.sendAync(testFrom, testTo, testMessage);
            }
            Test.stopTest();
        }

		// Assert
		List<SmsLog__c> logList = [ SELECT messageResult__c from SmsLog__c ];
		System.assertEquals(1, logList.size());
		System.assertEquals('success', logList[0].messageResult__c);
	}
}